"""initial migration

Revision ID: ec7121a523cd
Revises:
Create Date: 2025-03-14 03:17:09.719772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ec7121a523cd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ledger_entries",
        sa.Column(
            "operation",
            postgresql.ENUM(
                "DAILY_REWARD",
                "SIGNUP_CREDIT",
                "CREDIT_SPEND",
                "CREDIT_ADD",
                "CONTENT_CREATION",
                "CONTENT_ACCESS",
                name="healthai_ledger_operation",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.BIGINT(), nullable=False),
        sa.Column("nonce", sa.String(), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nonce"),
        schema="healthai",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ledger_entries", schema="healthai")
    # ### end Alembic commands ###
